# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: protocol/healthcheck.proto for package ''

require 'grpc'
require 'protocol/healthcheck_pb'

module Healthcheck
  class Service

    include GRPC::GenericService

    self.marshal_class_method = :encode
    self.unmarshal_class_method = :decode
    self.service_name = 'Healthcheck'

    rpc :Ok, HealthcheckRequest, HealthcheckResponse
  end

  Stub = Service.rpc_stub_class
end
