# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protocol/healthcheck.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "HealthcheckRequest" do
  end
  add_message "HealthcheckResponse" do
    optional :status, :enum, 1, "HealthcheckResponse.Status"
  end
  add_enum "HealthcheckResponse.Status" do
    value :Standby, 0
    value :Starting, 1
    value :Ready, 2
  end
end

HealthcheckRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("HealthcheckRequest").msgclass
HealthcheckResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("HealthcheckResponse").msgclass
HealthcheckResponse::Status = Google::Protobuf::DescriptorPool.generated_pool.lookup("HealthcheckResponse.Status").enummodule
