// Code generated by protoc-gen-go. DO NOT EDIT.
// source: service.proto

/*
Package service is a generated protocol buffer package.

It is generated from these files:
	service.proto

It has these top-level messages:
	GetReleaseInfoRequest
	ListReleasesRequest
	ListReleasesResponse
	ReleaseInfo
*/
package service

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type GetReleaseInfoRequest struct {
	Version string `protobuf:"bytes,1,opt,name=version" json:"version,omitempty"`
}

func (m *GetReleaseInfoRequest) Reset()                    { *m = GetReleaseInfoRequest{} }
func (m *GetReleaseInfoRequest) String() string            { return proto.CompactTextString(m) }
func (*GetReleaseInfoRequest) ProtoMessage()               {}
func (*GetReleaseInfoRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *GetReleaseInfoRequest) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

type ListReleasesRequest struct {
}

func (m *ListReleasesRequest) Reset()                    { *m = ListReleasesRequest{} }
func (m *ListReleasesRequest) String() string            { return proto.CompactTextString(m) }
func (*ListReleasesRequest) ProtoMessage()               {}
func (*ListReleasesRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type ListReleasesResponse struct {
	Releases []*ReleaseInfo `protobuf:"bytes,1,rep,name=releases" json:"releases,omitempty"`
}

func (m *ListReleasesResponse) Reset()                    { *m = ListReleasesResponse{} }
func (m *ListReleasesResponse) String() string            { return proto.CompactTextString(m) }
func (*ListReleasesResponse) ProtoMessage()               {}
func (*ListReleasesResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *ListReleasesResponse) GetReleases() []*ReleaseInfo {
	if m != nil {
		return m.Releases
	}
	return nil
}

type ReleaseInfo struct {
	Version         string `protobuf:"bytes,1,opt,name=version" json:"version,omitempty"`
	ReleaseDate     string `protobuf:"bytes,2,opt,name=release_date,json=releaseDate" json:"release_date,omitempty"`
	ReleaseNotesUrl string `protobuf:"bytes,3,opt,name=release_notes_url,json=releaseNotesUrl" json:"release_notes_url,omitempty"`
}

func (m *ReleaseInfo) Reset()                    { *m = ReleaseInfo{} }
func (m *ReleaseInfo) String() string            { return proto.CompactTextString(m) }
func (*ReleaseInfo) ProtoMessage()               {}
func (*ReleaseInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *ReleaseInfo) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *ReleaseInfo) GetReleaseDate() string {
	if m != nil {
		return m.ReleaseDate
	}
	return ""
}

func (m *ReleaseInfo) GetReleaseNotesUrl() string {
	if m != nil {
		return m.ReleaseNotesUrl
	}
	return ""
}

func init() {
	proto.RegisterType((*GetReleaseInfoRequest)(nil), "GetReleaseInfoRequest")
	proto.RegisterType((*ListReleasesRequest)(nil), "ListReleasesRequest")
	proto.RegisterType((*ListReleasesResponse)(nil), "ListReleasesResponse")
	proto.RegisterType((*ReleaseInfo)(nil), "ReleaseInfo")
}

func init() { proto.RegisterFile("service.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 240 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x91, 0x4d, 0x4b, 0xc4, 0x30,
	0x10, 0x86, 0x37, 0x2e, 0xf8, 0x31, 0xad, 0x5f, 0xe3, 0x56, 0xc2, 0x9e, 0xd6, 0x9c, 0x8a, 0x87,
	0x80, 0xeb, 0xc5, 0x8b, 0xe0, 0x41, 0x28, 0x82, 0x78, 0xa8, 0x78, 0x2e, 0x55, 0x47, 0x28, 0x94,
	0xa4, 0x66, 0xd2, 0xfe, 0x09, 0xff, 0xb4, 0x58, 0x53, 0x69, 0xa1, 0x1e, 0xf3, 0x3e, 0xf3, 0x32,
	0xc9, 0x13, 0x38, 0x64, 0x72, 0x5d, 0xf5, 0x46, 0xba, 0x71, 0xd6, 0x5b, 0x75, 0x05, 0x49, 0x46,
	0x3e, 0xa7, 0x9a, 0x4a, 0xa6, 0x07, 0xf3, 0x61, 0x73, 0xfa, 0x6c, 0x89, 0x3d, 0x4a, 0xd8, 0xeb,
	0xc8, 0x71, 0x65, 0x8d, 0x14, 0x1b, 0x91, 0x1e, 0xe4, 0xc3, 0x51, 0x25, 0x70, 0xf6, 0x58, 0xf1,
	0xd0, 0xe1, 0x50, 0x50, 0x77, 0xb0, 0x9a, 0xc6, 0xdc, 0x58, 0xc3, 0x84, 0x29, 0xec, 0xbb, 0x90,
	0x49, 0xb1, 0x59, 0xa6, 0xd1, 0x36, 0xd6, 0xe3, 0x7d, 0x7f, 0x54, 0x75, 0x10, 0x8d, 0xc0, 0xff,
	0x37, 0xc0, 0x0b, 0x88, 0x43, 0xa9, 0x78, 0x2f, 0x3d, 0xc9, 0x9d, 0x1e, 0x47, 0x21, 0xbb, 0x2f,
	0x3d, 0xe1, 0x25, 0x9c, 0x0e, 0x23, 0xc6, 0x7a, 0xe2, 0xa2, 0x75, 0xb5, 0x5c, 0xf6, 0x73, 0xc7,
	0x01, 0x3c, 0xfd, 0xe4, 0x2f, 0xae, 0xde, 0x7e, 0x09, 0x38, 0xc9, 0x6c, 0x58, 0xfd, 0xfc, 0xab,
	0x07, 0x6f, 0xe0, 0x68, 0x2a, 0x06, 0xcf, 0xf5, 0xac, 0xa9, 0xf5, 0xe4, 0x39, 0x6a, 0x81, 0xb7,
	0x10, 0x8f, 0x45, 0xe0, 0x4a, 0xcf, 0xe8, 0x5a, 0x27, 0x7a, 0xce, 0x96, 0x5a, 0xbc, 0xee, 0xf6,
	0x1f, 0x73, 0xfd, 0x1d, 0x00, 0x00, 0xff, 0xff, 0x3f, 0x42, 0x16, 0x97, 0xa9, 0x01, 0x00, 0x00,
}
