// Code generated by protoc-gen-go. DO NOT EDIT.
// source: weather.proto

/*
Package weather is a generated protocol buffer package.

It is generated from these files:
	weather.proto

It has these top-level messages:
	GetForecastDayRequest
	ForecastDayInfo
	GetForecastWeekRequest
	ForecastWeekInfo
*/
package weather

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type DayOfWeek int32

const (
	DayOfWeek_Sun DayOfWeek = 0
	DayOfWeek_Mon DayOfWeek = 1
	DayOfWeek_Tue DayOfWeek = 2
	DayOfWeek_Wed DayOfWeek = 3
	DayOfWeek_Thu DayOfWeek = 4
	DayOfWeek_Fri DayOfWeek = 5
	DayOfWeek_Sat DayOfWeek = 6
)

var DayOfWeek_name = map[int32]string{
	0: "Sun",
	1: "Mon",
	2: "Tue",
	3: "Wed",
	4: "Thu",
	5: "Fri",
	6: "Sat",
}
var DayOfWeek_value = map[string]int32{
	"Sun": 0,
	"Mon": 1,
	"Tue": 2,
	"Wed": 3,
	"Thu": 4,
	"Fri": 5,
	"Sat": 6,
}

func (x DayOfWeek) String() string {
	return proto.EnumName(DayOfWeek_name, int32(x))
}
func (DayOfWeek) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type TemperatureUnit int32

const (
	TemperatureUnit_Celsius    TemperatureUnit = 0
	TemperatureUnit_Fahrenheit TemperatureUnit = 1
)

var TemperatureUnit_name = map[int32]string{
	0: "Celsius",
	1: "Fahrenheit",
}
var TemperatureUnit_value = map[string]int32{
	"Celsius":    0,
	"Fahrenheit": 1,
}

func (x TemperatureUnit) String() string {
	return proto.EnumName(TemperatureUnit_name, int32(x))
}
func (TemperatureUnit) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type GetForecastDayRequest struct {
	Day DayOfWeek `protobuf:"varint,1,opt,name=day,enum=DayOfWeek" json:"day,omitempty"`
}

func (m *GetForecastDayRequest) Reset()                    { *m = GetForecastDayRequest{} }
func (m *GetForecastDayRequest) String() string            { return proto.CompactTextString(m) }
func (*GetForecastDayRequest) ProtoMessage()               {}
func (*GetForecastDayRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *GetForecastDayRequest) GetDay() DayOfWeek {
	if m != nil {
		return m.Day
	}
	return DayOfWeek_Sun
}

type ForecastDayInfo struct {
	Day                         DayOfWeek       `protobuf:"varint,1,opt,name=day,enum=DayOfWeek" json:"day,omitempty"`
	Temperature                 string          `protobuf:"bytes,2,opt,name=Temperature" json:"Temperature,omitempty"`
	Unit                        TemperatureUnit `protobuf:"varint,3,opt,name=unit,enum=TemperatureUnit" json:"unit,omitempty"`
	ChanceOfPrecipitation       int32           `protobuf:"varint,4,opt,name=ChanceOfPrecipitation" json:"ChanceOfPrecipitation,omitempty"`
	ForecastDescription         string          `protobuf:"bytes,5,opt,name=ForecastDescription" json:"ForecastDescription,omitempty"`
	DetailedForecastDescription string          `protobuf:"bytes,6,opt,name=DetailedForecastDescription" json:"DetailedForecastDescription,omitempty"`
}

func (m *ForecastDayInfo) Reset()                    { *m = ForecastDayInfo{} }
func (m *ForecastDayInfo) String() string            { return proto.CompactTextString(m) }
func (*ForecastDayInfo) ProtoMessage()               {}
func (*ForecastDayInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ForecastDayInfo) GetDay() DayOfWeek {
	if m != nil {
		return m.Day
	}
	return DayOfWeek_Sun
}

func (m *ForecastDayInfo) GetTemperature() string {
	if m != nil {
		return m.Temperature
	}
	return ""
}

func (m *ForecastDayInfo) GetUnit() TemperatureUnit {
	if m != nil {
		return m.Unit
	}
	return TemperatureUnit_Celsius
}

func (m *ForecastDayInfo) GetChanceOfPrecipitation() int32 {
	if m != nil {
		return m.ChanceOfPrecipitation
	}
	return 0
}

func (m *ForecastDayInfo) GetForecastDescription() string {
	if m != nil {
		return m.ForecastDescription
	}
	return ""
}

func (m *ForecastDayInfo) GetDetailedForecastDescription() string {
	if m != nil {
		return m.DetailedForecastDescription
	}
	return ""
}

type GetForecastWeekRequest struct {
}

func (m *GetForecastWeekRequest) Reset()                    { *m = GetForecastWeekRequest{} }
func (m *GetForecastWeekRequest) String() string            { return proto.CompactTextString(m) }
func (*GetForecastWeekRequest) ProtoMessage()               {}
func (*GetForecastWeekRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type ForecastWeekInfo struct {
	Forecasts []*ForecastDayInfo `protobuf:"bytes,1,rep,name=forecasts" json:"forecasts,omitempty"`
}

func (m *ForecastWeekInfo) Reset()                    { *m = ForecastWeekInfo{} }
func (m *ForecastWeekInfo) String() string            { return proto.CompactTextString(m) }
func (*ForecastWeekInfo) ProtoMessage()               {}
func (*ForecastWeekInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *ForecastWeekInfo) GetForecasts() []*ForecastDayInfo {
	if m != nil {
		return m.Forecasts
	}
	return nil
}

func init() {
	proto.RegisterType((*GetForecastDayRequest)(nil), "GetForecastDayRequest")
	proto.RegisterType((*ForecastDayInfo)(nil), "ForecastDayInfo")
	proto.RegisterType((*GetForecastWeekRequest)(nil), "GetForecastWeekRequest")
	proto.RegisterType((*ForecastWeekInfo)(nil), "ForecastWeekInfo")
	proto.RegisterEnum("DayOfWeek", DayOfWeek_name, DayOfWeek_value)
	proto.RegisterEnum("TemperatureUnit", TemperatureUnit_name, TemperatureUnit_value)
}

func init() { proto.RegisterFile("weather.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 380 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x92, 0xcd, 0xea, 0xd3, 0x40,
	0x14, 0xc5, 0x33, 0x4d, 0x3f, 0xe8, 0x2d, 0x36, 0xe3, 0x48, 0x6b, 0xa8, 0x2e, 0x42, 0x70, 0x11,
	0xba, 0x18, 0xa4, 0xea, 0x4e, 0x50, 0x6c, 0xa9, 0x28, 0x48, 0x25, 0x56, 0xba, 0x1e, 0xd3, 0x1b,
	0x32, 0x58, 0x27, 0x71, 0x32, 0x41, 0xfa, 0x16, 0xbe, 0x82, 0x6f, 0x2a, 0x99, 0x6a, 0x8d, 0xf9,
	0x87, 0xee, 0x0e, 0xe7, 0xcc, 0x09, 0x37, 0x3f, 0x0e, 0xdc, 0xfb, 0x81, 0xc2, 0x64, 0xa8, 0x79,
	0xa1, 0x73, 0x93, 0x87, 0x2f, 0x60, 0xf6, 0x16, 0xcd, 0x36, 0xd7, 0x98, 0x88, 0xd2, 0x6c, 0xc4,
	0x39, 0xc6, 0xef, 0x15, 0x96, 0x86, 0x3d, 0x06, 0xf7, 0x28, 0xce, 0x3e, 0x09, 0x48, 0x34, 0x5d,
	0x01, 0xdf, 0x88, 0xf3, 0x2e, 0x3d, 0x20, 0x7e, 0x8d, 0x6b, 0x3b, 0xfc, 0xd5, 0x03, 0xaf, 0x51,
	0x7a, 0xa7, 0xd2, 0xfc, 0x76, 0x83, 0x05, 0x30, 0xd9, 0xe3, 0xb7, 0x02, 0xb5, 0x30, 0x95, 0x46,
	0xbf, 0x17, 0x90, 0x68, 0x1c, 0x37, 0x2d, 0xf6, 0x04, 0xfa, 0x95, 0x92, 0xc6, 0x77, 0xed, 0x07,
	0x28, 0x6f, 0x64, 0x9f, 0x95, 0x34, 0xb1, 0x4d, 0xd9, 0x73, 0x98, 0xad, 0x33, 0xa1, 0x12, 0xdc,
	0xa5, 0x1f, 0x35, 0x26, 0xb2, 0x90, 0x46, 0x18, 0x99, 0x2b, 0xbf, 0x1f, 0x90, 0x68, 0x10, 0x77,
	0x87, 0xec, 0x29, 0x3c, 0xb8, 0x9e, 0x8b, 0x65, 0xa2, 0x65, 0x61, 0x3b, 0x03, 0x7b, 0x45, 0x57,
	0xc4, 0x5e, 0xc3, 0xa3, 0x0d, 0x1a, 0x21, 0x4f, 0x78, 0xec, 0x6a, 0x0e, 0x6d, 0xf3, 0xd6, 0x93,
	0xd0, 0x87, 0x79, 0x03, 0xad, 0x25, 0x71, 0x61, 0x1b, 0xbe, 0x01, 0xda, 0xb4, 0x2d, 0x3d, 0x0e,
	0xe3, 0xf4, 0x8f, 0x57, 0xfa, 0x24, 0x70, 0xa3, 0xc9, 0x8a, 0xf2, 0x16, 0xe2, 0xf8, 0xdf, 0x93,
	0xe5, 0x7b, 0x18, 0x5f, 0x09, 0xb3, 0x11, 0xb8, 0x9f, 0x2a, 0x45, 0x9d, 0x5a, 0x7c, 0xc8, 0x15,
	0x25, 0xb5, 0xd8, 0x57, 0x48, 0x7b, 0xb5, 0x38, 0xe0, 0x91, 0xba, 0xd6, 0xc9, 0x2a, 0xda, 0xaf,
	0xc5, 0x56, 0x4b, 0x3a, 0xb0, 0x2d, 0x61, 0xe8, 0x70, 0xc9, 0xc1, 0x6b, 0xc1, 0x66, 0x13, 0x18,
	0xad, 0xf1, 0x54, 0xca, 0xaa, 0xa4, 0x0e, 0x9b, 0x02, 0x6c, 0x45, 0xa6, 0x51, 0x65, 0x28, 0x0d,
	0x25, 0xab, 0x9f, 0x04, 0xbc, 0xc3, 0x65, 0x46, 0x7f, 0x2f, 0x64, 0x2f, 0x61, 0xfa, 0xff, 0x90,
	0xd8, 0x9c, 0x77, 0x2e, 0x6b, 0x71, 0xe7, 0xb7, 0x42, 0x87, 0xbd, 0x02, 0xaf, 0xc5, 0x8a, 0x3d,
	0xe4, 0xdd, 0xf4, 0x16, 0xf7, 0x79, 0x1b, 0x5e, 0xe8, 0x7c, 0x19, 0xda, 0x39, 0x3f, 0xfb, 0x1d,
	0x00, 0x00, 0xff, 0xff, 0xf0, 0x8e, 0xe4, 0x3f, 0xdf, 0x02, 0x00, 0x00,
}
